version: 2
jobs:
  # 全てのコミットで実行するタスク
  build:
    docker:
      # Node.jsのバージョンを指定する (使えるバージョンは https://hub.docker.com/r/circleci/node/tags/ を参照)
      - image: circleci/node:8.9.3
    steps:
      - checkout
      - run:
          name: Install Node Modules
          command: |
            npm install
            npm rebuild node-sass
            npm run build

  # dev環境デプロイ
  deploy_development:
    docker:
      - image: circleci/node:8.9.3
    steps:
      - checkout
      - run:
          name: build & deploy
          command: |
            sudo apt-get install -y python-pip
            sudo apt-get install python2.7-dev
            sudo pip install awscli
            npm install
            npm rebuild node-sass
            APP_ENV=development npm run build
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - deploy:
          command: |
            aws s3 sync public s3://dev.example.com/ --delete --region ap-northeast-1 --cache-control "no-cache" --acl public-read

  # stg環境デプロイ
  deploy_staging:
    docker:
      - image: circleci/node:8.9.3
    steps:
      - checkout
      - run:
          name: build & deploy
          command: |
            sudo apt-get install -y python-pip
            sudo apt-get install python2.7-dev
            sudo pip install awscli
            npm install
            npm rebuild node-sass
            APP_ENV=staging npm run build
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - deploy:
          command: |
            aws s3 sync public s3://stg.example.com/ --delete --region ap-northeast-1 --cache-control "no-cache" --acl public-read

  # 本番環境デプロイ
  deploy_production:
    docker:
      - image: circleci/node:8.9.3
    steps:
      - checkout
      - run:
          name: build & deploy
          command: |
            sudo apt-get install -y python-pip
            sudo apt-get install python2.7-dev
            sudo pip install awscli
            npm install
            npm rebuild node-sass
            APP_ENV=production npm run build
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - deploy:
          command: |
            aws s3 sync public s3://example.com/ --delete --region ap-northeast-1 --cache-control "no-cache" --acl public-read

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - deploy_development:
          filters:
            branches:
              only: develop

      - deploy_staging:
          filters:
            branches:
              only: master

      - deploy_production:
          filters:
            branches:
              only: production
